# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/benz/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),benz)

$(call add-radio-file-sha1-checked,radio/abl.img,cc793c9f41f428acfe038c0ffd6eb2e252629b39)
$(call add-radio-file-sha1-checked,radio/aop.img,66c54dfdd7fdb60dc108e1cd2b74631f1d52ef4f)
$(call add-radio-file-sha1-checked,radio/aop_config.img,0f3042f5d579f72694a4eac50eaa59b119fbe9d5)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d9f122302c212bd3bcfa332af84ef650baebbc68)
$(call add-radio-file-sha1-checked,radio/cpucp.img,b22d4605f51b1bc42a239cbb329276250675aa71)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c685af5d1b7e871b87c69201b933bf6771e252db)
$(call add-radio-file-sha1-checked,radio/dsp.img,1b594ddc7882de4846708c13ed10ebea84faf93e)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,aaeae1bba2623c04bb25b50a5c6b68017d5e3f0d)
$(call add-radio-file-sha1-checked,radio/hyp.img,2fdf84d682bf2e355b5ff9d447375dd92f9a7275)
$(call add-radio-file-sha1-checked,radio/imagefv.img,96e12bfa2378a68b66b7ac530a4b1329ee7926eb)
$(call add-radio-file-sha1-checked,radio/keymaster.img,bb7984c49fcb97205d763206932522426b05b652)
$(call add-radio-file-sha1-checked,radio/modem.img,a9c0b44d7211b98106a12a7827092c8ee8a236a4)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,98dd4dd4909be893360d24abfef25bf9a3bda318)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,c6258fc44e9cb6307ffc56afaa7778ab24856073)
$(call add-radio-file-sha1-checked,radio/qupfw.img,77ab5b20b9c3f7b5e046c4dd3fb60c5d79f13808)
$(call add-radio-file-sha1-checked,radio/shrm.img,1c05b0a93e2e69dbc1d79c143c14eda852f1b8a6)
$(call add-radio-file-sha1-checked,radio/splash.img,84e14653a04d30f754baa9e65b54069f368382bd)
$(call add-radio-file-sha1-checked,radio/tz.img,2ab8eebf88b8f4c3179659ae1c37ea79c3a71850)
$(call add-radio-file-sha1-checked,radio/uefi.img,bd607ba786e8500eceff9ae2d30238c0a6eb8d6c)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,50ff34d90e6e8a03164a5923e55dc5b274418406)
$(call add-radio-file-sha1-checked,radio/xbl.img,e8e7eca747517852900d34ebe7643db649c0514a)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,deef4ffb37899b0fcbbb9144b3e1ffa986006817)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,1463c6f711b6592a5c54c95432169b5a03f45e7e)

endif
